package com.idscodelabs.compose_form.app

import androidx.compose.runtime.Composable
import com.idscodelabs.compose_form.examples.validators.DateAfterValidatorExample
import com.idscodelabs.compose_form.examples.validators.DateBeforeValidatorExample
import com.idscodelabs.compose_form.examples.validators.EveryCharacterValidatorExampleCustom
import com.idscodelabs.compose_form.examples.validators.MaxLengthValidatorExample
import com.idscodelabs.compose_form.examples.validators.MinLengthValidatorExample
import com.idscodelabs.compose_form.examples.validators.MultipleValidatorExample
import com.idscodelabs.compose_form.examples.validators.MustBeTickedValidatorExample
import com.idscodelabs.compose_form.examples.validators.NotEmptyIfOtherNotPopulatedValidatorExample
import com.idscodelabs.compose_form.examples.validators.NotEmptyIfOtherPopulatedValidatorExample
import com.idscodelabs.compose_form.examples.validators.NotEmptyValidatorExample
import com.idscodelabs.compose_form.examples.validators.NumberOnlyValidatorExample
import com.idscodelabs.compose_form.examples.validators.RegexValidatorExample
import com.idscodelabs.compose_form.examples.validators.TimeAfterValidatorExample
import com.idscodelabs.compose_form.examples.validators.TimeBeforeValidatorExample

expect fun platformExamples(): List<Example>
